language: fortran

sudo: required
dist: trusty

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6

before_install:
- sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 50

script:
  - make clean
  - make uclchem
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
".travis.yml" [noeol] 15L, 251C
